name: Deploy

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  deploy-pypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-uv
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run tests
        run: |
          uv run pytest -r a src tests --doctest-modules
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: "${{ secrets.PYPI_TOKEN }}"
        run: |
          uv build
          uv publish
